name: Rebase Develop Branch after Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout develop branch
        run: |
          git pull
          git checkout develop
      - name: Rebase develop branch
        run: git rebase main
      - name: Push changes
        run: git push origin develop
